# Generated by Django 4.2.7 on 2025-12-10 09:39

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='TextChunks',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('start_time_seconds', models.FloatField()),
                ('duration', models.FloatField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('embedded', 'Embedded'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, to='transcripts.videos', to_field='video_id')),
            ],
            options={
                'db_table': 'text_chunks',
                'managed': True,
                'indexes': [models.Index(fields=['video', 'start_time_seconds'], name='text_chunks_video_i_efdf56_idx'), models.Index(fields=['status'], name='text_chunks_status_e46064_idx')],
            },
        ),
    ]
