# Generated by Django 4.2.7 on 2025-12-11 08:13

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_textchunks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textchunks',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
